[package]
name    = "crypto"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "benchmark"
path = "src/main.rs"

[features]
nightly = ["aes_crypto/nightly"]

[dependencies]
aes_crypto = "1"
